### PR TITLE
Various updates to wiki

### PR DESCRIPTION
**Pull request by mycpphurts**
## Update includes:

- Addition of Guides page
    - And first Download entry
- Changes to the side bar and top bar to remove vitepress templates
- Few updates to landing page.

**Review and merge if everything is A-OK thanks!**

### CODE REVIEW

**Comment by mycpphurts** [comment]
Note: Wiki folder is so the URL goes like `/wiki/download`

**Comment by kermeow** [comment]
> Note: Wiki folder is so the URL goes like `/wiki/download`

why? the wiki is hosted at wiki.rhythia.net
why should it be wiki.rhythia.net/wiki

**Comment by mycpphurts** [comment]
Hold on ima uh
do a funny

**Comment by mycpphurts** [comment]
Lmk what u think on discord kerm thxxxx 😵‍💫🇵🇹

**Pull request merged**
